runtime: python27
api_version: 1
threadsafe: true
service: front

handlers:
- url: /
  static_files: dist/jevelina/index.html
  upload: dist/jevelina/index.html

- url: /restricted
  static_files: dist/jevelina/index.html
  upload: dist/jevelina/index.html

- url: /
  static_dir: dist/jevelina