runtime: python27
api_version: 1
threadsafe: true
service: front

handlers:
- url: /(.*\.(js|css|svg|png)(|\.map))$
  static_files: dist/jevelina/\1
  upload: dist/jevelina/(.*)(|\.map)

- url: /.*
  static_files: dist/jevelina/index.html
  upload: dist/jevelina/.*